---
- name: Configure nginx with HTTPS support
  hosts: all
  become: true
  vars:
    nginx_version: "1.28.1"

  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: "nginx-{{ nginx_version }}"
        state: present

    - name: Generate self-signed SSL certificate
      ansible.builtin.command:
        cmd: >
          openssl req -x509 -nodes -days 365 -newkey rsa:2048
          -keyout /etc/pki/tls/private/nginx-cert.key
          -out /etc/pki/tls/certs/nginx-cert.crt
          -subj "/C=NZ/ST=Auckland/L=Auckland/O=HANTT/CN=custom-template-dev"
        creates: /etc/pki/tls/certs/nginx-cert.crt


    - name: Configure nginx.conf
      ansible.builtin.copy:
        dest: /etc/nginx/nginx.conf
        mode: '0644'
        content: |
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log;
          pid /run/nginx.pid;
          include /usr/share/nginx/modules/*.conf;

          events {
              worker_connections 1024;
          }

          http {
              log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';

              access_log  /var/log/nginx/access.log  main;

              sendfile            on;
              tcp_nopush          on;
              tcp_nodelay         on;
              keepalive_timeout   65;
              types_hash_max_size 4096;

              include             /etc/nginx/mime.types;
              default_type        application/octet-stream;

              # Load modular configuration files
              include /etc/nginx/conf.d/*.conf;
          }
      notify: Restart Nginx

    - name: Configure HTTP to HTTPS redirect
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/http-redirect.conf
        mode: '0644'
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              server_name _;
              return 301 https://$host$request_uri;
          }
      notify: Restart Nginx

    - name: Configure HTTPS server
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/https-server.conf
        mode: '0644'
        content: |
          server {
              listen 443 ssl default_server;
              listen [::]:443 ssl default_server;
              server_name _;
              http2 on;

              ssl_certificate "/etc/pki/tls/certs/nginx-cert.crt";
              ssl_certificate_key "/etc/pki/tls/private/nginx-cert.key";
              ssl_session_cache shared:SSL:1m;
              ssl_session_timeout  10m;
              ssl_ciphers PROFILE=SYSTEM;
              ssl_prefer_server_ciphers on;

              location / {
                  root /usr/share/nginx/html;
                  index index.html index.htm;
              }
              include /etc/nginx/includes/*.conf;
          }
      notify: Restart Nginx

    - name: Enable nginx service
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
